### ISSUE TITLE
exampleSite params.footer typo

### ISSUE THREAD

**Issue by Normandabald** [StaticMania/roxo-hugo#46]
https://github.com/StaticMania/roxo-hugo/blob/eac3f49bc57315701ca29498525078bd28c1338b/exampleSite/config.toml#L102

```toml
    secondary_button_url = "portfolio"

  [params.footer]
    params.footer.qr_print = false
    # Footer Contact Info
    [params.footer.contactInfo]
```

Typo/bug on line 102 prevents the example site from starting.
Should be `qr_print = false`
